version: "3.3"

services:
   mysql-node1:
     build: ./mysql-node1
     container_name: mysql-node1
     hostname: mysql-node1
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Qwerty1234
       MYSQL_DATABASE: example
       MYSQL_USER: example_user
       MYSQL_PASSWORD: 123456
     ports:
      - target: 3306
        published: 13306
        protocol: tcp
        mode: host