GRANT REPLICATION SLAVE ON *.* TO 'rpl_user'@'%' IDENTIFIED BY '123456';
CHANGE MASTER TO MASTER_HOST='mysql-node2',MASTER_USER='rpl_user', MASTER_PASSWORD='123456', MASTER_LOG_FILE='mysql-bin.000003', MASTER_LOG_POS=154;
START SLAVE;